const data = [
    {
        "_id": "65dcac2c39989295b89ef8c6",
        "numero": "BL-0068",
        "date": "2024-02-26T15:19:26.094Z",
        "client": {
            "_id": "65c5c293eee1fad456fd6b79",
            "code": "CL-0024",
            "raisonSociale": "Nadhmi",
            "matriculeFiscale": "2200019949828",
            "telephone": "96062453"
        },
        "type_transport": "1",
        "nom_chauffeur": "",
        "matricule_vehicule": "",
        "depotpv": {
            "_id": "6572d58701a5ed58b2b96f62",
            "libelle": "KHARROUBA",
            "code_unique": "pv01"
        },
        "utilisateur": {
            "_id": "6569d909e54c20448510a684",
            "nom": "TestAdmin TestAdmin"
        },
        "bloque": false,
        "totalBrutHT": 7.5,
        "totalRemise": 0,
        "totalHT": 7.5,
        "totalFodec": 0.075,
        "totalDC": 0,
        "totalNetHT": 7.575,
        "totalTVA": 1.439,
        "totalRedevance": 0,
        "timbreFiscale": 0,
        "totalTTC": 9.014,
        "totalPayer": 0,
        "resteAPayer": 9.014,
        "documentPrecedent": [
            {
                "_id": "65dcab2d39989295b89ef84e",
                "numero": "BCC-0007",
                "date": "2024-02-26T15:15:40.605Z",
                "client": {
                    "_id": "65c5c293eee1fad456fd6b79",
                    "code": "CL-0024",
                    "raisonSociale": "Nadhmi",
                    "matriculeFiscale": "2200019949828",
                    "telephone": "96062453"
                },
                "type_transport": "1",
                "nom_chauffeur": "",
                "matricule_vehicule": "",
                "depotpv": {
                    "_id": "6572d58701a5ed58b2b96f62",
                    "libelle": "KHARROUBA",
                    "code_unique": "pv01"
                },
                "utilisateur": {
                    "_id": "6569d909e54c20448510a684",
                    "nom": "TestAdmin TestAdmin"
                },
                "bloque": false,
                "totalBrutHT": 15,
                "totalRemise": 0,
                "totalHT": 15,
                "totalFodec": 0.15,
                "totalDC": 0,
                "totalNetHT": 15.15,
                "totalTVA": 2.879,
                "totalRedevance": 0,
                "timbreFiscale": 0,
                "totalTTC": 18.029,
                "totalPayer": 0,
                "resteAPayer": 18.029,
                "documentPrecedent": [],
                "documentSuivant": [
                    {
                        "_id": "65dcab5e39989295b89ef86e",
                        "table": "bonlivraisons",
                        "numero": "BL-0067",
                        "date": "2024-02-26T15:16:23.317Z",
                        "totalTTC": 9.014
                    },
                    {
                        "_id": "65dcac2c39989295b89ef8c6",
                        "table": "bonlivraisons",
                        "numero": "BL-0068",
                        "date": "2024-02-26T15:19:26.094Z",
                        "totalTTC": 9.014
                    }
                ],
                "numeroDocClient": "",
                "dateDocClient": null,
                "notes": "",
                "lignes": [
                    {
                        "numero": 1,
                        "article": {
                            "_id": "65ad1e1a0e866e29e2499a1d",
                            "reference": "B12",
                            "codeBarre": "65",
                            "designation": "BRIQUE 12",
                            "typeArticle": "1",
                            "categorie": {
                                "_id": "65ab93df0e866e29e24988ae",
                                "libelle": "CONSTRUCTION"
                            },
                            "famille": {
                                "_id": "65ab97440e866e29e2498975",
                                "libelle": "BRIQUE ROUGE"
                            },
                            "sousFamille": {
                                "_id": "65ab9db50e866e29e2498a71",
                                "libelle": "BRIQUE 12 TROUS"
                            },
                            "venduPar": "1",
                            "valeurStock": 0,
                            "qteEnStock": 9448,
                            "pmp": 0,
                            "unite1": {
                                "_id": "659b039118a7182611bef510",
                                "libelle": "PIECE"
                            },
                            "archive": true,
                            "lotSerieActive": false,
                            "enVente": true,
                            "enAchat": true,
                            "prixFourn": 0.6,
                            "remiseF": 0,
                            "isFodecA": false,
                            "prixFodecA": 0,
                            "isDC": false,
                            "tauxDC": 0,
                            "prixDC": 0,
                            "tauxTVA": 19,
                            "montantTVA": 0.114,
                            "prixAchat": 0.6,
                            "prixAchatTTC": 0.714,
                            "prixRevient": 0.6,
                            "redevance": 0,
                            "prixRevientTTC": 0.714,
                            "margeAppliqueeSur": "2",
                            "tauxMarge": 25,
                            "prixMarge": 0.15,
                            "prixVenteHT": 0.75,
                            "isFodecV": true,
                            "prixFodecV": 0.007,
                            "montantTVAVente": 0.144,
                            "prixTTC": 0.901,
                            "pVenteConseille": 0,
                            "coefficient": 1,
                            "marque": {
                                "_id": "65aba0cf0e866e29e2498b0d",
                                "libelle": "JEMMEL"
                            },
                            "unite2": {
                                "_id": "659b039118a7182611bef510",
                                "libelle": "PIECE"
                            },
                            "modele": "",
                            "refFournisseur": "",
                            "description": "",
                            "frais": null,
                            "estPack": false,
                            "sousArticles": [],
                            "stockReaprov": 0,
                            "stockMin": 0,
                            "stockMax": 130,
                            "longueur": 0,
                            "largeur": 0,
                            "hauteur": 0,
                            "surface": 0,
                            "volume": 0,
                            "poids": 0,
                            "emplacement": [],
                            "colisage": [],
                            "remiseMontant": 0,
                            "sansRemise": true,
                            "plafondRemise": 0,
                            "prixParQte": true,
                            "prixQte": [],
                            "enPromotion": true,
                            "promotion": [],
                            "pointFidelite": true,
                            "nbPointFix": false,
                            "nbPointVar": true,
                            "fidelite": [],
                            "documents": [],
                            "enBalance": false,
                            "estNouveau": true,
                            "isDCVente": true,
                            "tauxDCVente": 0,
                            "prixDCVente": 0,
                            "isRedevanceVente": true,
                            "prixNetVenteHT": 0.757,
                            "code_societe": "s01",
                            "deleted": false,
                            "active": true,
                            "modification_notes": []
                        },
                        "quantiteLivre": 20,
                        "quantiteRestante": 0,
                        "quantiteUnite1": 20,
                        "unite1": {
                            "_id": "659b039118a7182611bef510",
                            "libelle": "PIECE"
                        },
                        "quantiteUnite2": 20,
                        "unite2": {
                            "_id": "659b039118a7182611bef510",
                            "libelle": "PIECE"
                        },
                        "depot_pv": {
                            "_id": "6572d58701a5ed58b2b96f62",
                            "code_unique": "pv01",
                            "libelle": "KHARROUBA"
                        },
                        "prixAchatUnitaireHT": 0.6,
                        "prixVenteBrutHT": 0.75,
                        "tauxremise": 0,
                        "remiseMontant": 0,
                        "prixVenteUnitaireHT": 0.75,
                        "isFodec": true,
                        "tauxFodec": 1,
                        "montantFodec": 0.007,
                        "isDC": true,
                        "tauxDC": 0,
                        "montantDC": 0,
                        "prixVenteUnitaireNetHT": 0.757,
                        "tauxTVA": 19,
                        "montantTVA": 0.144,
                        "redevance": 0,
                        "prixVenteUnitaireTTC": 0.901,
                        "totalBrutHT": 15,
                        "totalRemise": 0,
                        "totalHT": 15,
                        "totalFodec": 0.15,
                        "totalDC": 0,
                        "totalNetHT": 15.15,
                        "totalTVA": 2.879,
                        "totalRedevance": 0,
                        "timbreFiscale": 0,
                        "totalTTC": 18.029,
                        "gainCommercialUnitaire": 0.157,
                        "gainCommercialTotal": 3.14,
                        "gainReelUnitaire": 0.157,
                        "gainReelTotal": 3.14,
                        "deleted": false,
                        "_id": "65dcab2d39989295b89ef84f"
                    }
                ],
                "code_societe": "s01",
                "code_exercice": "24",
                "code_depotpv": "pv01",
                "deleted": false,
                "addition_note": {
                    "date": "2024-02-26T15:15:57.046Z",
                    "utilisateur": "6569d909e54c20448510a684"
                },
                "modification_notes": [],
                "__v": 0,
                "chauffeur": {},
                "sessionCaisse": {},
                "vehicule": {}
            }
        ],
        "documentSuivant": [
            {
                "_id": "65dcab5e39989295b89ef86e",
                "table": "bonlivraisons",
                "numero": "BL-0067",
                "date": "2024-02-26T15:16:23.317Z",
                "totalTTC": 9.014
            }
        ],
        "numeroDocClient": "",
        "dateDocClient": null,
        "notes": "",
        "lignes": [
            {
                "numero": 1,
                "article": {
                    "_id": "65ad1e1a0e866e29e2499a1d",
                    "reference": "B12",
                    "codeBarre": "65",
                    "designation": "BRIQUE 12",
                    "typeArticle": "1",
                    "categorie": {
                        "_id": "65ab93df0e866e29e24988ae",
                        "libelle": "CONSTRUCTION"
                    },
                    "famille": {
                        "_id": "65ab97440e866e29e2498975",
                        "libelle": "BRIQUE ROUGE"
                    },
                    "sousFamille": {
                        "_id": "65ab9db50e866e29e2498a71",
                        "libelle": "BRIQUE 12 TROUS"
                    },
                    "venduPar": "1",
                    "valeurStock": 0,
                    "qteEnStock": 9448,
                    "pmp": 0,
                    "unite1": {
                        "_id": "659b039118a7182611bef510",
                        "libelle": "PIECE"
                    },
                    "archive": true,
                    "lotSerieActive": false,
                    "enVente": true,
                    "enAchat": true,
                    "prixFourn": 0.6,
                    "remiseF": 0,
                    "isFodecA": false,
                    "prixFodecA": 0,
                    "isDC": false,
                    "tauxDC": 0,
                    "prixDC": 0,
                    "tauxTVA": 19,
                    "montantTVA": 0.114,
                    "prixAchat": 0.6,
                    "prixAchatTTC": 0.714,
                    "prixRevient": 0.6,
                    "redevance": 0,
                    "prixRevientTTC": 0.714,
                    "margeAppliqueeSur": "2",
                    "tauxMarge": 25,
                    "prixMarge": 0.15,
                    "prixVenteHT": 0.75,
                    "isFodecV": true,
                    "prixFodecV": 0.007,
                    "montantTVAVente": 0.144,
                    "prixTTC": 0.901,
                    "pVenteConseille": 0,
                    "coefficient": 1,
                    "marque": {
                        "_id": "65aba0cf0e866e29e2498b0d",
                        "libelle": "JEMMEL"
                    },
                    "unite2": {
                        "_id": "659b039118a7182611bef510",
                        "libelle": "PIECE"
                    },
                    "modele": "",
                    "refFournisseur": "",
                    "description": "",
                    "frais": null,
                    "stockReaprov": 0,
                    "stockMin": 0,
                    "stockMax": 130,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "surface": 0,
                    "volume": 0,
                    "poids": 0,
                    "remiseMontant": 0,
                    "sansRemise": true,
                    "plafondRemise": 0,
                    "prixParQte": true,
                    "prixQte": [],
                    "enPromotion": true,
                    "promotion": [],
                    "pointFidelite": true,
                    "nbPointFix": false,
                    "nbPointVar": true,
                    "fidelite": [],
                    "documents": [],
                    "enBalance": false,
                    "estNouveau": true,
                    "isDCVente": true,
                    "tauxDCVente": 0,
                    "prixDCVente": 0,
                    "isRedevanceVente": true,
                    "prixNetVenteHT": 0.757,
                    "code_societe": "s01",
                    "deleted": false,
                    "active": true,
                    "estPack": false,
                    "sousArticles": [],
                    "emplacement": [],
                    "colisage": [],
                    "modification_notes": []
                },
                "quantiteLivre": 10,
                "quantiteRestante": 10,
                "quantiteUnite1": 10,
                "unite1": {
                    "_id": "659b039118a7182611bef510",
                    "libelle": "PIECE"
                },
                "quantiteUnite2": 10,
                "unite2": {
                    "_id": "659b039118a7182611bef510",
                    "libelle": "PIECE"
                },
                "depot_pv": {
                    "_id": "6572d58701a5ed58b2b96f62",
                    "code_unique": "pv01",
                    "libelle": "KHARROUBA"
                },
                "prixAchatUnitaireHT": 0.6,
                "prixVenteBrutHT": 0.75,
                "tauxremise": 0,
                "remiseMontant": 0,
                "prixVenteUnitaireHT": 0.75,
                "isFodec": true,
                "tauxFodec": 1,
                "montantFodec": 0.007,
                "isDC": true,
                "tauxDC": 0,
                "montantDC": 0,
                "prixVenteUnitaireNetHT": 0.757,
                "tauxTVA": 19,
                "montantTVA": 0.144,
                "redevance": 0,
                "prixVenteUnitaireTTC": 0.901,
                "totalBrutHT": 7.5,
                "totalRemise": 0,
                "totalHT": 7.5,
                "totalFodec": 0.075,
                "totalDC": 0,
                "totalNetHT": 7.575,
                "totalTVA": 1.439,
                "totalRedevance": 0,
                "timbreFiscale": 0,
                "totalTTC": 9.014,
                "gainCommercialUnitaire": 0.157,
                "gainCommercialTotal": 1.57,
                "gainReelUnitaire": 0.157,
                "gainReelTotal": 1.57,
                "deleted": false,
                "_id": "65dcab2d39989295b89ef84f"
            }
        ],
        "code_societe": "s01",
        "code_exercice": "24",
        "code_depotpv": "pv01",
        "deleted": false,
        "addition_note": {
            "date": "2024-02-26T15:20:12.407Z",
            "utilisateur": "6569d909e54c20448510a684"
        },
        "modification_notes": [],
        "__v": 0,
        "reglements": []
    },
    {
        "_id": "65dcab5e39989295b89ef86e",
        "numero": "BL-0067",
        "date": "2024-02-26T15:16:23.317Z",
        "client": {
            "_id": "65c5c293eee1fad456fd6b79",
            "code": "CL-0024",
            "raisonSociale": "Nadhmi",
            "matriculeFiscale": "2200019949828",
            "telephone": "96062453"
        },
        "type_transport": "1",
        "nom_chauffeur": "",
        "matricule_vehicule": "",
        "depotpv": {
            "_id": "6572d58701a5ed58b2b96f62",
            "libelle": "KHARROUBA",
            "code_unique": "pv01"
        },
        "utilisateur": {
            "_id": "6569d909e54c20448510a684",
            "nom": "TestAdmin TestAdmin"
        },
        "bloque": false,
        "totalBrutHT": 7.5,
        "totalRemise": 0,
        "totalHT": 7.5,
        "totalFodec": 0.075,
        "totalDC": 0,
        "totalNetHT": 7.575,
        "totalTVA": 1.439,
        "totalRedevance": 0,
        "timbreFiscale": 0,
        "totalTTC": 9.014,
        "totalPayer": 0,
        "resteAPayer": 9.014,
        "documentPrecedent": [
            {
                "_id": "65dcab2d39989295b89ef84e",
                "numero": "BCC-0007",
                "date": "2024-02-26T15:15:40.605Z",
                "client": {
                    "_id": "65c5c293eee1fad456fd6b79",
                    "code": "CL-0024",
                    "raisonSociale": "Nadhmi",
                    "matriculeFiscale": "2200019949828",
                    "telephone": "96062453"
                },
                "type_transport": "1",
                "nom_chauffeur": "",
                "matricule_vehicule": "",
                "depotpv": {
                    "_id": "6572d58701a5ed58b2b96f62",
                    "libelle": "KHARROUBA",
                    "code_unique": "pv01"
                },
                "utilisateur": {
                    "_id": "6569d909e54c20448510a684",
                    "nom": "TestAdmin TestAdmin"
                },
                "bloque": false,
                "totalBrutHT": 15,
                "totalRemise": 0,
                "totalHT": 15,
                "totalFodec": 0.15,
                "totalDC": 0,
                "totalNetHT": 15.15,
                "totalTVA": 2.879,
                "totalRedevance": 0,
                "timbreFiscale": 0,
                "totalTTC": 18.029,
                "totalPayer": 0,
                "resteAPayer": 18.029,
                "documentPrecedent": [],
                "documentSuivant": [
                    {
                        "_id": "65dcab5e39989295b89ef86e",
                        "table": "bonlivraisons",
                        "numero": "BL-0067",
                        "date": "2024-02-26T15:16:23.317Z",
                        "totalTTC": 9.014
                    },
                    {
                        "_id": "65dcac2c39989295b89ef8c6",
                        "table": "bonlivraisons",
                        "numero": "BL-0068",
                        "date": "2024-02-26T15:19:26.094Z",
                        "totalTTC": 9.014
                    }
                ],
                "numeroDocClient": "",
                "dateDocClient": null,
                "notes": "",
                "lignes": [
                    {
                        "numero": 1,
                        "article": {
                            "_id": "65ad1e1a0e866e29e2499a1d",
                            "reference": "B12",
                            "codeBarre": "65",
                            "designation": "BRIQUE 12",
                            "typeArticle": "1",
                            "categorie": {
                                "_id": "65ab93df0e866e29e24988ae",
                                "libelle": "CONSTRUCTION"
                            },
                            "famille": {
                                "_id": "65ab97440e866e29e2498975",
                                "libelle": "BRIQUE ROUGE"
                            },
                            "sousFamille": {
                                "_id": "65ab9db50e866e29e2498a71",
                                "libelle": "BRIQUE 12 TROUS"
                            },
                            "venduPar": "1",
                            "valeurStock": 0,
                            "qteEnStock": 9448,
                            "pmp": 0,
                            "unite1": {
                                "_id": "659b039118a7182611bef510",
                                "libelle": "PIECE"
                            },
                            "archive": true,
                            "lotSerieActive": false,
                            "enVente": true,
                            "enAchat": true,
                            "prixFourn": 0.6,
                            "remiseF": 0,
                            "isFodecA": false,
                            "prixFodecA": 0,
                            "isDC": false,
                            "tauxDC": 0,
                            "prixDC": 0,
                            "tauxTVA": 19,
                            "montantTVA": 0.114,
                            "prixAchat": 0.6,
                            "prixAchatTTC": 0.714,
                            "prixRevient": 0.6,
                            "redevance": 0,
                            "prixRevientTTC": 0.714,
                            "margeAppliqueeSur": "2",
                            "tauxMarge": 25,
                            "prixMarge": 0.15,
                            "prixVenteHT": 0.75,
                            "isFodecV": true,
                            "prixFodecV": 0.007,
                            "montantTVAVente": 0.144,
                            "prixTTC": 0.901,
                            "pVenteConseille": 0,
                            "coefficient": 1,
                            "marque": {
                                "_id": "65aba0cf0e866e29e2498b0d",
                                "libelle": "JEMMEL"
                            },
                            "unite2": {
                                "_id": "659b039118a7182611bef510",
                                "libelle": "PIECE"
                            },
                            "modele": "",
                            "refFournisseur": "",
                            "description": "",
                            "frais": null,
                            "estPack": false,
                            "sousArticles": [],
                            "stockReaprov": 0,
                            "stockMin": 0,
                            "stockMax": 130,
                            "longueur": 0,
                            "largeur": 0,
                            "hauteur": 0,
                            "surface": 0,
                            "volume": 0,
                            "poids": 0,
                            "emplacement": [],
                            "colisage": [],
                            "remiseMontant": 0,
                            "sansRemise": true,
                            "plafondRemise": 0,
                            "prixParQte": true,
                            "prixQte": [],
                            "enPromotion": true,
                            "promotion": [],
                            "pointFidelite": true,
                            "nbPointFix": false,
                            "nbPointVar": true,
                            "fidelite": [],
                            "documents": [],
                            "enBalance": false,
                            "estNouveau": true,
                            "isDCVente": true,
                            "tauxDCVente": 0,
                            "prixDCVente": 0,
                            "isRedevanceVente": true,
                            "prixNetVenteHT": 0.757,
                            "code_societe": "s01",
                            "deleted": false,
                            "active": true,
                            "modification_notes": []
                        },
                        "quantiteLivre": 20,
                        "quantiteRestante": 0,
                        "quantiteUnite1": 20,
                        "unite1": {
                            "_id": "659b039118a7182611bef510",
                            "libelle": "PIECE"
                        },
                        "quantiteUnite2": 20,
                        "unite2": {
                            "_id": "659b039118a7182611bef510",
                            "libelle": "PIECE"
                        },
                        "depot_pv": {
                            "_id": "6572d58701a5ed58b2b96f62",
                            "code_unique": "pv01",
                            "libelle": "KHARROUBA"
                        },
                        "prixAchatUnitaireHT": 0.6,
                        "prixVenteBrutHT": 0.75,
                        "tauxremise": 0,
                        "remiseMontant": 0,
                        "prixVenteUnitaireHT": 0.75,
                        "isFodec": true,
                        "tauxFodec": 1,
                        "montantFodec": 0.007,
                        "isDC": true,
                        "tauxDC": 0,
                        "montantDC": 0,
                        "prixVenteUnitaireNetHT": 0.757,
                        "tauxTVA": 19,
                        "montantTVA": 0.144,
                        "redevance": 0,
                        "prixVenteUnitaireTTC": 0.901,
                        "totalBrutHT": 15,
                        "totalRemise": 0,
                        "totalHT": 15,
                        "totalFodec": 0.15,
                        "totalDC": 0,
                        "totalNetHT": 15.15,
                        "totalTVA": 2.879,
                        "totalRedevance": 0,
                        "timbreFiscale": 0,
                        "totalTTC": 18.029,
                        "gainCommercialUnitaire": 0.157,
                        "gainCommercialTotal": 3.14,
                        "gainReelUnitaire": 0.157,
                        "gainReelTotal": 3.14,
                        "deleted": false,
                        "_id": "65dcab2d39989295b89ef84f"
                    }
                ],
                "code_societe": "s01",
                "code_exercice": "24",
                "code_depotpv": "pv01",
                "deleted": false,
                "addition_note": {
                    "date": "2024-02-26T15:15:57.046Z",
                    "utilisateur": "6569d909e54c20448510a684"
                },
                "modification_notes": [],
                "__v": 0,
                "chauffeur": {},
                "sessionCaisse": {},
                "vehicule": {}
            }
        ],
        "documentSuivant": [],
        "numeroDocClient": "",
        "dateDocClient": null,
        "notes": "",
        "lignes": [
            {
                "numero": 1,
                "article": {
                    "_id": "65ad1e1a0e866e29e2499a1d",
                    "reference": "B12",
                    "codeBarre": "65",
                    "designation": "BRIQUE 12",
                    "typeArticle": "1",
                    "categorie": {
                        "_id": "65ab93df0e866e29e24988ae",
                        "libelle": "CONSTRUCTION"
                    },
                    "famille": {
                        "_id": "65ab97440e866e29e2498975",
                        "libelle": "BRIQUE ROUGE"
                    },
                    "sousFamille": {
                        "_id": "65ab9db50e866e29e2498a71",
                        "libelle": "BRIQUE 12 TROUS"
                    },
                    "venduPar": "1",
                    "valeurStock": 0,
                    "qteEnStock": 9448,
                    "pmp": 0,
                    "unite1": {
                        "_id": "659b039118a7182611bef510",
                        "libelle": "PIECE"
                    },
                    "archive": true,
                    "lotSerieActive": false,
                    "enVente": true,
                    "enAchat": true,
                    "prixFourn": 0.6,
                    "remiseF": 0,
                    "isFodecA": false,
                    "prixFodecA": 0,
                    "isDC": false,
                    "tauxDC": 0,
                    "prixDC": 0,
                    "tauxTVA": 19,
                    "montantTVA": 0.114,
                    "prixAchat": 0.6,
                    "prixAchatTTC": 0.714,
                    "prixRevient": 0.6,
                    "redevance": 0,
                    "prixRevientTTC": 0.714,
                    "margeAppliqueeSur": "2",
                    "tauxMarge": 25,
                    "prixMarge": 0.15,
                    "prixVenteHT": 0.75,
                    "isFodecV": true,
                    "prixFodecV": 0.007,
                    "montantTVAVente": 0.144,
                    "prixTTC": 0.901,
                    "pVenteConseille": 0,
                    "coefficient": 1,
                    "marque": {
                        "_id": "65aba0cf0e866e29e2498b0d",
                        "libelle": "JEMMEL"
                    },
                    "unite2": {
                        "_id": "659b039118a7182611bef510",
                        "libelle": "PIECE"
                    },
                    "modele": "",
                    "refFournisseur": "",
                    "description": "",
                    "frais": null,
                    "stockReaprov": 0,
                    "stockMin": 0,
                    "stockMax": 130,
                    "longueur": 0,
                    "largeur": 0,
                    "hauteur": 0,
                    "surface": 0,
                    "volume": 0,
                    "poids": 0,
                    "remiseMontant": 0,
                    "sansRemise": true,
                    "plafondRemise": 0,
                    "prixParQte": true,
                    "prixQte": [],
                    "enPromotion": true,
                    "promotion": [],
                    "pointFidelite": true,
                    "nbPointFix": false,
                    "nbPointVar": true,
                    "fidelite": [],
                    "documents": [],
                    "enBalance": false,
                    "estNouveau": true,
                    "isDCVente": true,
                    "tauxDCVente": 0,
                    "prixDCVente": 0,
                    "isRedevanceVente": true,
                    "prixNetVenteHT": 0.757,
                    "code_societe": "s01",
                    "deleted": false,
                    "active": true,
                    "estPack": false,
                    "sousArticles": [],
                    "emplacement": [],
                    "colisage": [],
                    "modification_notes": []
                },
                "quantiteLivre": 0,
                "quantiteRestante": 20,
                "quantiteUnite1": 10,
                "unite1": {
                    "_id": "659b039118a7182611bef510",
                    "libelle": "PIECE"
                },
                "quantiteUnite2": 10,
                "unite2": {
                    "_id": "659b039118a7182611bef510",
                    "libelle": "PIECE"
                },
                "depot_pv": {
                    "_id": "6572d58701a5ed58b2b96f62",
                    "code_unique": "pv01",
                    "libelle": "KHARROUBA"
                },
                "prixAchatUnitaireHT": 0.6,
                "prixVenteBrutHT": 0.75,
                "tauxremise": 0,
                "remiseMontant": 0,
                "prixVenteUnitaireHT": 0.75,
                "isFodec": true,
                "tauxFodec": 1,
                "montantFodec": 0.007,
                "isDC": true,
                "tauxDC": 0,
                "montantDC": 0,
                "prixVenteUnitaireNetHT": 0.757,
                "tauxTVA": 19,
                "montantTVA": 0.144,
                "redevance": 0,
                "prixVenteUnitaireTTC": 0.901,
                "totalBrutHT": 7.5,
                "totalRemise": 0,
                "totalHT": 7.5,
                "totalFodec": 0.075,
                "totalDC": 0,
                "totalNetHT": 7.575,
                "totalTVA": 1.439,
                "totalRedevance": 0,
                "timbreFiscale": 0,
                "totalTTC": 9.014,
                "gainCommercialUnitaire": 0.157,
                "gainCommercialTotal": 1.57,
                "gainReelUnitaire": 0.157,
                "gainReelTotal": 1.57,
                "deleted": false,
                "_id": "65dcab2d39989295b89ef84f"
            }
        ],
        "code_societe": "s01",
        "code_exercice": "24",
        "code_depotpv": "pv01",
        "deleted": false,
        "addition_note": {
            "date": "2024-02-26T15:16:46.235Z",
            "utilisateur": "6569d909e54c20448510a684"
        },
        "modification_notes": [],
        "__v": 0,
        "reglements": []
    }
]

export default data;