export const aioTableLabels = [
    {
      text: 'New',
      textClass: 'text-green-600',
      bgClass: 'bg-green-600/10',
      previewClass: 'bg-green-600'
    },
    {
      text: 'Lead',
      textClass: 'text-cyan-600',
      bgClass: 'bg-cyan-600/10',
      previewClass: 'bg-cyan-600'
    },
    {
      text: 'In Progress',
      textClass: 'text-teal-600',
      bgClass: 'bg-teal-600/10',
      previewClass: 'bg-teal-600'
    },
    {
      text: 'Completed',
      textClass: 'text-purple-600',
      bgClass: 'bg-purple-600/10',
      previewClass: 'bg-purple-600'
    }
  ];
  
  export const aioClientData = [
    {
      id: 0,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0], aioTableLabels[1]]
    },
    {
      id: 1,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 2,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[3]]
    },
    {
      id: 3,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[3]]
    },
    {
      id: 4,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 5,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 6,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[2]]
    },
    {
      id: 7,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0], aioTableLabels[1]]
    },
    {
      id: 8,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 9,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[2]]
    },
    {
      id: 10,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 11,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[3]]
    },
    {
      id: 12,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[3]]
    },
    {
      id: 13,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[3]]
    },
    {
      id: 14,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[2]]
    },
    {
      id: 15,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 16,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 17,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 18,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 19,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[2]]
    },
    {
      id: 20,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 21,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 22,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 23,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 24,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 25,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[3]]
    },
    {
      id: 26,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[0]]
    },
    {
      id: 27,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 28,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[1]]
    },
    {
      id: 29,
      nom: 'salah alaha',
      titre: 'Dejesus',
      gouv: 'Chang',
      idpays: 12,
      CP: 8057,
      Delegation: 'Munjor',
      localite: 'angleterre -London',
      adresse: 'dejesus.chang@yourcompany.biz',
      labels: [aioTableLabels[2]]
    }
  ];
  