export const aioTableLabels = [
    {
      text: 'New',
      textClass: 'text-green-600',
      bgClass: 'bg-green-600/10',
      previewClass: 'bg-green-600'
    },
    {
      text: 'Lead',
      textClass: 'text-cyan-600',
      bgClass: 'bg-cyan-600/10',
      previewClass: 'bg-cyan-600'
    },
    {
      text: 'In Progress',
      textClass: 'text-teal-600',
      bgClass: 'bg-teal-600/10',
      previewClass: 'bg-teal-600'
    },
    {
      text: 'Completed',
      textClass: 'text-purple-600',
      bgClass: 'bg-purple-600/10',
      previewClass: 'bg-purple-600'
    }
  ];
  
  export const aioContactData = [
    {
      id: 0,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alii',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0], aioTableLabels[1]]
    },
    {
      id: 1,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'muhamed',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 2,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[3]]
    },
    {
      id: 3,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'rami jawwadi',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[3]]
    },
    {
      id: 4,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 5,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 6,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[2]]
    },
    {
      id: 7,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0], aioTableLabels[1]]
    },
    {
      id: 8,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 9,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[2]]
    },
    {
      id: 10,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 11,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[3]]
    },
    {
      id: 12,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[3]]
    },
    {
      id: 13,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[3]]
    },
    {
      id: 14,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[2]]
    },
    {
      id: 15,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 16,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 17,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 18,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 19,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[2]]
    },
    {
      id: 20,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 21,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 22,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 23,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 24,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 25,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[3]]
    },
    {
      id: 26,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[0]]
    },
    {
      id: 27,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 28,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[1]]
    },
    {
      id: 29,
      typeContact:"cdd",
      titre: 'Dejesus',
      civilité: 'Dejecsus civilite',
      nomPrenom: 'salah alaha',
      tel:+216555555,
      Mobilitè: 'Monastir',
      email: 'dejesus.chang@yourcompany.biz',
      remarques: "pas de remarques tous est parfait Mr",
      labels: [aioTableLabels[2]]
    }
  ];
  