export const composantsTableData = [
    {
      id:'1',
      reference: 'Ref1',
      designation: 'Item 1',
      prixAchat: 10.00,
      tauxTVA: '20%',
      prixHT: 8.33,
      prixTTC: 10.00,
      quantite: 2,
      totalHT: 16.66,
      totalTTC: 20.00,
    },
    {
      id:'2',
      reference: 'Ref1',
      designation: 'Item 1',
      prixAchat: 10.00,
      tauxTVA: '20%',
      prixHT: 8.33,
      prixTTC: 10.00,
      quantite: 2,
      totalHT: 16.66,
      totalTTC: 20.00,
    },
    {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref1',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },
      {
        id:'2',
        reference: 'Ref29',
        designation: 'Item 1',
        prixAchat: 10.00,
        tauxTVA: '20%',
        prixHT: 8.33,
        prixTTC: 10.00,
        quantite: 2,
        totalHT: 16.66,
        totalTTC: 20.00,
      },

]